---
title: "eco_maps"
author: "JT Miller"
date: "1/11/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Eco data mapping
## The purpose of this script is to analyze bee occurrence data based upon california's enviromental map found here: https://www.epa.gov/eco-research/ecoregion-download-files-state-region-9 
```{r}
library(sf)
library(leaflet)
library(rgdal)
library(leafgl)

```


### Bringing in the occurrence data from GBIF, all bees for the USA DOI https://doi.org/10.15468/dl.4qr9s2
```{r}
specimen_data <- read.delim(file="filter_polygon/bee_occurrences_usa.txt",header=TRUE)

specimen_data <- subset(specimen_data, !is.na(order) & !is.na(decimalLongitude) & !is.na(decimalLatitude))
```


### Mapping out California Level 3
```{r}
eco_map <- sf::read_sf("filter_polygon/cali_ecoregions_3/ca_eco_l3.shp") %>% 
  sf::st_transform('+proj=longlat +datum=WGS84')

leaflet() %>% addTiles() %>% 
  addPolygons(data = eco_map) 
  #addCircleMarkers(data = specimen_data, lat = ~decimalLatitude, lng = ~decimalLongitude)
```


### Bounding specimen data and mapping
```{r}
specimen_data_w_crs <- st_as_sf(specimen_data, coords = c('decimalLongitude', 'decimalLatitude'), crs = 4326)

specimen_bounded <- specimen_data_w_crs[eco_map,]

specimen_bounded_sep <- specimen_bounded %>%
  dplyr::mutate(decimalLatitude = sf::st_coordinates(.)[,2],
                decimalLongitude = sf::st_coordinates(.)[,1])

leaflet() %>% addTiles() %>% 
  #addPolygons(data = eco_map) +
  addCircleMarkers(data = specimen_bounded_sep, lat = ~decimalLatitude, lng = ~decimalLongitude)

```

```{r}
#Error: Can only handle POLYGONs, please cast your MULTIPOLYGON to POLYGON using sf::st_cast

eco_map_polygon <- sf::st_cast(eco_map, "POLYGON")

#convert sf to sp for use with other functions
eco_map_polygon_sp<-as(eco_map_polygon, "Spatial")
#convert sp to sf for use with this function 
eco_map_polygon_sp<-as(eco_map_polygon_sp, "sf")

options(viewer = NULL)
leaflet() %>%
  addGlPolygons(data = eco_map_polygon) %>%
  addGlPoints(data = specimen_bounded_sep, group = "pts") #Unfortunately this doesnt include the ecoregions as desired since changing from a multipolygon to a polygon type deletes the internal bounds. 
```




### Mapping out California Level 4
```{r}
eco_map4 <- sf::read_sf("filter_polygon/cali_ecoregions_4/ca_eco_l4.shp") %>% 
  sf::st_transform('+proj=longlat +datum=WGS84')


leaflet() %>% addTiles() %>% 
  addPolygons(data = eco_map4)

#ahahahah we will not be using this in the initial analysis...
```

