---
title: "Leaflet_maps"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# This document is focused on exploring the package leaflet in terms of our occurrence data. The goal is to integrate the filtering method into polygons on the interactive maps that leaflet offers, and then transition this to a shiny web application

```{r}
#Loading in packages
library(leaflet)
library(leaflet.extras)
library(rgdal)
library(sf)
library(raster)
```

```{r}
copr_boundary <- readOGR("COPR_Boundary_2010/COPR_boundary2010.shp")
occurrence_data <- read.csv("occur5.csv")
specimen_data <- read.delim(file="occurrence.txt",header=TRUE)
copr_boundary_st <- st_read("COPR_Boundary_2010/COPR_boundary2010.shp")
```

```{r}
#Apparently the polygon shape file needs to be in the CRS of the occurrence data for this to work. 
copr_latlon <- spTransform(copr_boundary, CRS("+proj=longlat +datum=WGS84"))
```

```{r}
#Trying to create variables with assigned CRS? https://rstudio.github.io/leaflet/projections.html 

espg4326 <- leafletCRS(crsClass = "L.Proj.CRS", code = "ESPG:4326", 
                       proj4def = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs", resolutions = 2^(13:-1), 
                       origin = c(0,0))
```





```{r}
specimen_data_w_crs <- st_as_sf(specimen_data, coords = c('decimalLongitude', 'decimalLatitude'), crs = 4326) #Assigning the CRS to WGS84

specimen_data_transformed <- st_transform(specimen_data_w_crs, 
                             st_crs(copr_boundary_st)) #Transforming the CRS
                                 
specimen_data_bounded <- specimen_data_transformed[copr_boundary_st,] #So apparently it needs the variable that st_read was used on in order to use this subsetting method. Performing it with readOGR does not work. 

#we also need to create new columns that specify the long and latitude since that was lost in the crs transformation. 
specimen_data_bounded_sep <- specimen_data_bounded %>%
  dplyr::mutate(decimalLatitude = sf::st_coordinates(.)[,2],
                decimalLongitude = sf::st_coordinates(.)[,1])
```

```{r}
#Now lets try projecting the map in the crs variable we created with leaflet. 
leaflet(options = leafletOptions(worldCopyJump = F, crs = espg4326)) %>% 
  addPolygons(data = copr_boundary_st, group = "Coal Oil Point Reserve") %>% 
  addCircleMarkers(data = specimen_data_bounded_sep, lat = ~decimalLatitude, lng = ~decimalLongitude, group = "Occurrence Data")
#The warning messages are concerning. This probably needs to be adjusted.
```


```{r}
#Warning message was inquired on stackoverflow: https://stackoverflow.com/questions/57223853/how-to-apply-spatial-polygons-to-leaflet-map-using-shp 

copr_map <- sf::read_sf("COPR_Boundary_2010/COPR_boundary2010.shp") %>% 
  sf::st_transform('+proj=longlat +datum=WGS84') #this line of code is correct

specimen_bounded <- specimen_data_w_crs[copr_map,]

specimen_bounded_sep <- specimen_bounded %>%
  dplyr::mutate(decimalLatitude = sf::st_coordinates(.)[,2],
                decimalLongitude = sf::st_coordinates(.)[,1])

map <- leaflet() %>% addTiles() %>% 
  addPolygons(data = copr_map, group = "Coal Oil Point Reserve") %>% 
  addCircleMarkers(data = specimen_bounded_sep, lat = ~decimalLatitude, lng = ~decimalLongitude, group = "Occurrence Data") %>% 
  #layer control
  addLayersControl(
    #baseGroups = "Occurrence Data", 
    overlayGroups = c("Coal Oil Point Reserve", "Occurrence Data"),
    options = layersControlOptions(collapsed = TRUE) 
  )

map

```


 

```{r}
#This produces an unfiltered map that shows circle markers for all of the occurrence points

#I also added a layer control option that allows you to toggle on and off the polygon boundary layer. Still working on a solution to getting the data points to filter. https://rstudio.github.io/leaflet/showhide.html 
map <- leaflet() %>% addTiles() %>% 
  addPolygons(data = copr_latlon, group = "Coal Oil Point Reserve") %>% 
  addCircleMarkers(data = specimen_data, lat = ~decimalLatitude, lng = ~decimalLongitude, group = "Occurrence Data") %>% 
  #layer control
  addLayersControl(
    #baseGroups = "Occurrence Data", 
    overlayGroups = c("Coal Oil Point Reserve", "Occurrence Data"),
    options = layersControlOptions(collapsed = TRUE) 
  )

map

```

